name: Continuous testing
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Test and coverage
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Run tests and generate coverage reports
        run: uv run --frozen pytest --cov --cov-report=xml
        if: always()

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: always()
